<?php

function provider_page_attachments(array &$attachments) {
    $url = \Drupal::request()->getRequestUri();
    if($url=='/provider' || $url == '/refused') {
        $attachments['#attached']['library'][] = 'provider/provider_css';
        $attachments['#attached']['library'][] = 'provider/module_js';
    }
    if($url=='/provider') {
        $attachments['#attached']['library'][] = 'provider/provider_js';
    }
    if($url=='/refused') {
        $attachments['#attached']['library'][] = 'provider/refuse_js';
    }
    if (substr($url,0,-1)=='/contract_create/'){
        $attachments['#attached']['library'][] = 'provider/create_css';
        $attachments['#attached']['library'][] = 'provider/create_js';
    }
    if (substr($url,0,-1)=='/contract/'){
        $attachments['#attached']['library'][] = 'provider/contract';
    }

}
function provider_theme() {
    return [
        'page__provider' => [
            'template' => 'page--provider',
        ],
        'page__refused' => [
            'template' => 'page--provider',
        ],
        'page__contracts' => [
            'template' => 'page--contracts',
        ],
    ];
}