<?php

function provider_page_attachments(array &$attachments) {
    $url = \Drupal::request()->getRequestUri();
    if($url=='/provider' || $url == '/refused') {
        $attachments['#attached']['library'][] = 'provider/provider_css';
        $attachments['#attached']['library'][] = 'provider/module_js';
    }
    if($url=='/provider' || $url=='/processed') {
        $attachments['#attached']['library'][] = 'provider/provider_js';
    }
    if($url=='/refused') {
        $attachments['#attached']['library'][] = 'provider/refuse_js';
    }
    if (!(stristr($url, '/contract_create/') === FALSE)){
        $attachments['#attached']['library'][] = 'provider/create_css';
        $attachments['#attached']['library'][] = 'provider/create_js';
    }
    if (!(stristr($url, '/contract/') === FALSE)){
        $attachments['#attached']['library'][] = 'provider/contract';
    }
    if (!(stristr($url, '/contracts') === FALSE)){
        $attachments['#attached']['library'][] = 'provider/contracts_libs';
    }
    if($url=='/user/proposed' || $url=='/user/confirmed' || $url=='/user/executed') {
        $attachments['#attached']['library'][] = 'provider/user_contracts';
    }
}
function provider_theme() {
    return [
        'page__provider' => [
            'template' => 'page--provider',
        ],
        'page__processed' => [
            'template' => 'page--provider',
        ],
        'page__refused' => [
            'template' => 'page--provider',
        ],
        'page__contracts' => [
            'template' => 'page--contracts',
        ],
        'page__user__proposed' => [
            'template' => 'page--user-contracts',
        ],
        'page__user__confirmed' => [
            'template' => 'page--user-contracts',
        ],
        'page__user__executed' => [
            'template' => 'page--user-contracts',
        ],
    ];
}
